/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Tugas12;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author ASUS
 */
public class Ubah extends javax.swing.JDialog {

    public Ubah(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        resetFormState();
        setLocationRelativeTo(null);
    }
    private void resetFormState() {
        lblPass.setVisible(false);
        btnUbah.setVisible(false);
        jPasswordField1.setVisible(false);
        lblTutup.setVisible(false);
        lblBuka1.setVisible(false);
        tfUser.setEditable(true);
        tfUser.setText("");
        jPasswordField1.setText("");
        jPasswordField1.setEchoChar('*');
    }
    public void bersih() {
        tfUser.setText("");
        jPasswordField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        lblPass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblTutup = new javax.swing.JLabel();
        lblBuka1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 221, 240));

        lblBack.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblBack.setText("<");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("UBAH");

        tfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUserActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(204, 255, 204));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        lblPass.setText("Password:");

        jLabel2.setText("Username:");

        btnCari.setBackground(new java.awt.Color(224, 249, 230));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setText("CARI & VERIF");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");

        lblTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas12/Password.png"))); // NOI18N
        lblTutup.setText("jLabel6");
        lblTutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTutupMouseClicked(evt);
            }
        });

        lblBuka1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas12/Password.png"))); // NOI18N
        lblBuka1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuka1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBack)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btnUbah))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPass, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jPasswordField1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCari))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblBuka1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuka1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnUbah)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        Login y = new Login();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void tfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUserActionPerformed
        if (tfUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi username dulu!");
        } else {
            btnCari.doClick();
        }
    }//GEN-LAST:event_tfUserActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (jPasswordField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Password harap diisi");
            return;
        }
        String newPassword = new String(jPasswordField1.getPassword());
        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Apakah Anda yakin ingin mengubah password?",
                "Konfirmasi Ubah Password",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBOTugas12PU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();

            String user = tfUser.getText();
            Login_1 x = em.find(Login_1.class, user);
            x.setPassword(newPassword);
            em.merge(x);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Berhasil diubah");
            em.close();
            emf.close();
            this.dispose();
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        if (tfUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Username Terlebih Dahulu");
            return;
        } 
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PBOTugas12PU");
            EntityManager em = emf.createEntityManager();    
        try {
            em.getTransaction().begin();
            String user = tfUser.getText();
            Login_1 y = em.find(Login_1.class, user);
            if (y == null) {
                JOptionPane.showMessageDialog(null, "Username tidak ditemukan");
                bersih();
                tfUser.requestFocus();
            } else {
                JPasswordField isiJawaban = new JPasswordField();
                Object[] message = {
                    "Pertanyaan Keamanan Anda:",
                    y.getPertanyaan(),
                    "Jawaban:", isiJawaban
                };
                int option = JOptionPane.showConfirmDialog(
                        null,
                        message,
                        "Verifikasi Keamanan",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE
                );
                if (option == JOptionPane.OK_OPTION) {
                    String jawaban = new String(isiJawaban.getPassword());
                    if (jawaban.trim().equalsIgnoreCase(y.getJawaban())) {
                        lblPass.setVisible(true);
                        btnUbah.setVisible(true);
                        jPasswordField1.setVisible(true);
                        lblBuka1.setVisible(true);
                        lblTutup.setVisible(false);
                        jPasswordField1.requestFocus();
//                        JOptionPane.showMessageDialog(null,
//                                "Verifikasi berhasil!\nSilakan masukkan password baru di form.",
//                                "Berhasil",
//                                JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null,
                                "Jawaban salah!\nPastikan jawaban sesuai dengan yang Anda buat saat pendaftaran.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        tfUser.requestFocus();
                    }
                }
            }
            em.getTransaction().commit();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void lblTutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTutupMouseClicked
        jPasswordField1.setEchoChar('*');
        lblTutup.setVisible(false);
        lblBuka1.setVisible(true);
    }//GEN-LAST:event_lblTutupMouseClicked

    private void lblBuka1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuka1MouseClicked
        jPasswordField1.setEchoChar((char) 0);
        lblTutup.setVisible(true);
        lblBuka1.setVisible(false);
    }//GEN-LAST:event_lblBuka1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Ubah dialog = new Ubah(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBuka1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTutup;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
